:bind: "0.0.0.0"
:port: 4567

:repo_abspath: "/home/chenyh/os/tmp"
:result_abspath: "/home/chenyh/os/tmp/result"
:repos:
        - :name: "autobuild_tester"
          :url: "git://github.com/chyh1990/autobuild_tester.git"
          :blacklist:
          :build_timeout_min: 10
          :run_timeout_min: 30
          :filters:
                - [ "ext", [".c", ".h", ".S", ".sh", ".s", ""] ]

